/*
 * RewardSciences.PCL
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/27/2016
 */
using System;
using RewardSciences.PCL.Controllers;
using RewardSciences.PCL.Http.Client;

namespace RewardSciences.PCL
{
    public partial class RewardSciencesClient
    {

        /// <summary>
        /// Singleton access to Rewards controller
        /// </summary>
        public Rewards Rewards
        {
            get
            {
                return RewardSciences.PCL.Controllers.Rewards.Instance;
            }
        }

        /// <summary>
        /// Singleton access to RewardCategories controller
        /// </summary>
        public RewardCategories RewardCategories
        {
            get
            {
                return RewardSciences.PCL.Controllers.RewardCategories.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Users controller
        /// </summary>
        public Users Users
        {
            get
            {
                return RewardSciences.PCL.Controllers.Users.Instance;
            }
        }

        /// <summary>
        /// Singleton access to Activities controller
        /// </summary>
        public Activities Activities
        {
            get
            {
                return RewardSciences.PCL.Controllers.Activities.Instance;
            }
        }

        /// <summary>
        /// The shared http client to use for all API calls
        /// </summary>
        public IHttpClient SharedHttpClient
        {
            get
            {
                return BaseController.ClientInstance;
            }
            set
            {
                BaseController.ClientInstance = value;
            }        
        }
        
        /// <summary>
        /// Default constructor
        /// </summary>
        public RewardSciencesClient() { }

        /// <summary>
        /// Client initialization constructor
        /// </summary>
        public RewardSciencesClient(string oAuthAccessToken)
        {
            Configuration.OAuthAccessToken = oAuthAccessToken;
        }
    }
}